package context

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/ashvinbhat/ox/internal/personas"
	"github.com/ashvinbhat/ox/internal/skills"
	"github.com/ashvinbhat/yoke/task"
)

// Generator creates AGENTS.md files for task workspaces.
type Generator struct {
	oxHome     string
	personaDir string
	skillsDir  string
}

// NewGenerator creates a new context generator.
func NewGenerator(oxHome string) *Generator {
	return &Generator{
		oxHome:     oxHome,
		personaDir: filepath.Join(oxHome, "personas"),
		skillsDir:  filepath.Join(oxHome, "skills"),
	}
}

// TaskContext holds all context for generating AGENTS.md.
type TaskContext struct {
	Task     *task.Task
	Notes    []task.Note
	Events   []task.Event
	Parent   *task.Task   // Parent task (if any)
	Children []*task.Task // Child tasks (if any)
	Blockers []*task.Task // Tasks blocking this one (resolved)
	Persona  string
	Skills   []string // Explicitly requested skills (legacy)
	Repos    []string
	TaskType string   // bug, feature, refactor, etc. (for skill matching)
}

// Generate creates an AGENTS.md file in the workspace and symlinks CLAUDE.md to it.
func (g *Generator) Generate(workspacePath string, ctx *TaskContext) error {
	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf("# Task #%d: %s\n\n", ctx.Task.Seq, ctx.Task.Title))

	// Status section
	sb.WriteString("## Status\n")
	sb.WriteString(fmt.Sprintf("%s | P%d", strings.ToUpper(string(ctx.Task.Status)), ctx.Task.Priority))
	if len(ctx.Task.Tags) > 0 {
		sb.WriteString(fmt.Sprintf(" | Tags: %s", strings.Join(ctx.Task.Tags, ", ")))
	}
	sb.WriteString("\n\n")

	// Context/Body
	if ctx.Task.Body != "" {
		sb.WriteString("## Context\n")
		sb.WriteString(ctx.Task.Body)
		sb.WriteString("\n\n")
	}

	// Notes
	if len(ctx.Notes) > 0 {
		sb.WriteString("## Notes\n")
		for _, note := range ctx.Notes {
			sb.WriteString(fmt.Sprintf("- %s: %s\n", note.CreatedAt.Format("2006-01-02"), note.Content))
		}
		sb.WriteString("\n")
	}

	// Dependencies section
	g.writeDependencies(&sb, ctx)

	// Hierarchy section
	g.writeHierarchy(&sb, ctx)

	// Recent activity
	if len(ctx.Events) > 0 {
		sb.WriteString("## Recent Activity\n")
		// Show last 10 events
		limit := 10
		if len(ctx.Events) < limit {
			limit = len(ctx.Events)
		}
		for i := len(ctx.Events) - limit; i < len(ctx.Events); i++ {
			e := ctx.Events[i]
			if e.OldValue != "" && e.NewValue != "" {
				sb.WriteString(fmt.Sprintf("- %s: %s → %s\n", e.EventType, e.OldValue, e.NewValue))
			} else if e.NewValue != "" {
				sb.WriteString(fmt.Sprintf("- %s: %s\n", e.EventType, e.NewValue))
			} else {
				sb.WriteString(fmt.Sprintf("- %s\n", e.EventType))
			}
		}
		sb.WriteString("\n")
	}

	// Related files from git history
	if len(ctx.Repos) > 0 {
		relatedFiles := g.findRelatedFiles(workspacePath, ctx.Repos, ctx.Task.Title)
		if len(relatedFiles) > 0 {
			sb.WriteString("## Related Files (from git history)\n")
			for _, rf := range relatedFiles {
				sb.WriteString(fmt.Sprintf("- %s (%d commits)\n", rf.Path, rf.Commits))
			}
			sb.WriteString("\n")
		}
	}

	// External links
	if ctx.Task.NotionURL != nil && *ctx.Task.NotionURL != "" {
		sb.WriteString("## External\n")
		sb.WriteString(fmt.Sprintf("Notion: %s\n\n", *ctx.Task.NotionURL))
	}

	// Repos in workspace
	if len(ctx.Repos) > 0 {
		sb.WriteString("## Workspace Repos\n")
		for _, r := range ctx.Repos {
			sb.WriteString(fmt.Sprintf("- %s/\n", r))
		}
		sb.WriteString("\n")
	}

	// Persona
	if ctx.Persona != "" {
		sb.WriteString("---\n\n")
		if reg, err := personas.LoadRegistry(g.oxHome); err == nil {
			if p, ok := reg.Get(ctx.Persona); ok {
				sb.WriteString(fmt.Sprintf("# Persona: %s\n", p.Name))
				if p.Role != "" {
					sb.WriteString(fmt.Sprintf("**Role:** %s\n\n", p.Role))
				}
				sb.WriteString(p.Content)
				sb.WriteString("\n")
			}
		}
	}

	// Skills - auto-inject based on tags, persona, task type
	g.writeSkills(&sb, workspacePath, ctx)

	// Footer
	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("Generated by ox at %s\n", time.Now().Format(time.RFC3339)))

	// Write AGENTS.md
	agentsPath := filepath.Join(workspacePath, "AGENTS.md")
	if err := os.WriteFile(agentsPath, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("write AGENTS.md: %w", err)
	}

	// Create CLAUDE.md symlink pointing to AGENTS.md
	claudePath := filepath.Join(workspacePath, "CLAUDE.md")
	os.Remove(claudePath) // Remove if exists
	if err := os.Symlink("AGENTS.md", claudePath); err != nil {
		return fmt.Errorf("create CLAUDE.md symlink: %w", err)
	}

	return nil
}

// writeDependencies writes the blocked by section.
func (g *Generator) writeDependencies(sb *strings.Builder, ctx *TaskContext) {
	if len(ctx.Blockers) == 0 && len(ctx.Task.Blockers) == 0 {
		return
	}

	sb.WriteString("## Blocked By\n")
	if len(ctx.Blockers) > 0 {
		for _, b := range ctx.Blockers {
			status := strings.ToLower(string(b.Status))
			sb.WriteString(fmt.Sprintf("- #%d: %s [%s]\n", b.Seq, b.Title, status))
		}
	} else {
		// Fallback to IDs if we couldn't resolve
		for _, id := range ctx.Task.Blockers {
			sb.WriteString(fmt.Sprintf("- %s\n", id))
		}
	}
	sb.WriteString("\n")
}

// writeSkills auto-injects skills based on tags, persona, and task type.
func (g *Generator) writeSkills(sb *strings.Builder, workspacePath string, ctx *TaskContext) {
	// Load skills registry
	reg, err := skills.LoadRegistry(g.oxHome)
	if err != nil {
		return // No skills registry
	}

	// Collect skills to include
	var skillsToInclude []*skills.Skill
	skillNames := make(map[string]bool)

	// 1. Auto-match from registry based on tags, persona, task type
	matched := reg.MatchForTask(ctx.Task.Tags, ctx.Persona, ctx.TaskType)
	for _, s := range matched {
		if !skillNames[s.Name] {
			skillsToInclude = append(skillsToInclude, s)
			skillNames[s.Name] = true
		}
	}

	// 2. Include explicitly requested skills (legacy)
	for _, name := range ctx.Skills {
		if skillNames[name] {
			continue
		}
		if s, ok := reg.Get(name); ok {
			skillsToInclude = append(skillsToInclude, s)
			skillNames[name] = true
		}
	}

	// 3. Include workspace-injected skills from .skills/
	wsSkillsDir := filepath.Join(workspacePath, ".skills")
	if entries, err := os.ReadDir(wsSkillsDir); err == nil {
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
				continue
			}
			name := strings.TrimSuffix(e.Name(), ".md")
			if skillNames[name] {
				continue
			}
			// Create a temporary skill for workspace-injected ones
			skillsToInclude = append(skillsToInclude, &skills.Skill{
				Name: name,
				File: e.Name(),
			})
			skillNames[name] = true
		}
	}

	if len(skillsToInclude) == 0 {
		return
	}

	sb.WriteString("---\n\n")
	sb.WriteString("# Skills\n\n")

	for _, skill := range skillsToInclude {
		// Try workspace .skills/ first, then global
		var content string
		wsPath := filepath.Join(workspacePath, ".skills", skill.File)
		if data, err := os.ReadFile(wsPath); err == nil {
			content = string(data)
		} else if c, err := reg.GetContent(skill); err == nil {
			content = c
		} else {
			continue // Skip if can't load
		}

		sb.WriteString(fmt.Sprintf("## %s\n", skill.Name))
		if skill.Description != "" {
			sb.WriteString(fmt.Sprintf("_%s_\n\n", skill.Description))
		}
		sb.WriteString(content)
		sb.WriteString("\n\n")
	}
}

// writeHierarchy writes parent and children info.
func (g *Generator) writeHierarchy(sb *strings.Builder, ctx *TaskContext) {
	if ctx.Parent == nil && len(ctx.Children) == 0 {
		return
	}

	sb.WriteString("## Hierarchy\n")

	if ctx.Parent != nil {
		sb.WriteString(fmt.Sprintf("Parent: #%d %s\n", ctx.Parent.Seq, ctx.Parent.Title))
	}

	if len(ctx.Children) > 0 {
		sb.WriteString("Children:\n")
		for _, child := range ctx.Children {
			status := g.statusIcon(child.Status)
			sb.WriteString(fmt.Sprintf("  %s #%d: %s\n", status, child.Seq, child.Title))
		}
	}
	sb.WriteString("\n")
}

// statusIcon returns an icon for the status.
func (g *Generator) statusIcon(status task.Status) string {
	switch status {
	case task.StatusPending:
		return "○"
	case task.StatusActive:
		return "◐"
	case task.StatusInProgress:
		return "●"
	case task.StatusBlocked:
		return "⊘"
	case task.StatusDone:
		return "✓"
	case task.StatusDropped:
		return "✗"
	default:
		return "?"
	}
}

// RelatedFile represents a file related to the task based on git history.
type RelatedFile struct {
	Path    string
	Commits int
}

// findRelatedFiles searches git history for files related to task keywords.
func (g *Generator) findRelatedFiles(workspacePath string, repos []string, taskTitle string) []RelatedFile {
	var results []RelatedFile

	// Extract keywords from task title
	keywords := extractKeywords(taskTitle)
	if len(keywords) == 0 {
		return nil
	}

	for _, repoName := range repos {
		repoPath := filepath.Join(workspacePath, repoName)
		if _, err := os.Stat(repoPath); err != nil {
			continue
		}

		// Search git log for commits mentioning keywords
		for _, keyword := range keywords {
			files := searchGitHistory(repoPath, keyword)
			for path, commits := range files {
				// Prefix with repo name for clarity
				fullPath := filepath.Join(repoName, path)
				results = append(results, RelatedFile{Path: fullPath, Commits: commits})
			}
		}
	}

	// Dedupe and sort by commit count
	seen := make(map[string]int)
	for _, rf := range results {
		if existing, ok := seen[rf.Path]; ok {
			if rf.Commits > existing {
				seen[rf.Path] = rf.Commits
			}
		} else {
			seen[rf.Path] = rf.Commits
		}
	}

	var deduped []RelatedFile
	for path, commits := range seen {
		deduped = append(deduped, RelatedFile{Path: path, Commits: commits})
	}

	sort.Slice(deduped, func(i, j int) bool {
		return deduped[i].Commits > deduped[j].Commits
	})

	// Limit to top 10
	if len(deduped) > 10 {
		deduped = deduped[:10]
	}

	return deduped
}

// extractKeywords extracts meaningful words from a title.
func extractKeywords(title string) []string {
	// Common words to ignore
	stopWords := map[string]bool{
		"the": true, "a": true, "an": true, "and": true, "or": true,
		"to": true, "for": true, "of": true, "in": true, "on": true,
		"with": true, "add": true, "fix": true, "update": true, "remove": true,
		"implement": true, "refactor": true, "create": true, "make": true,
	}

	words := strings.Fields(strings.ToLower(title))
	var keywords []string
	for _, w := range words {
		// Clean punctuation
		w = strings.Trim(w, ".,!?:;()[]{}\"'")
		if len(w) < 3 {
			continue
		}
		if stopWords[w] {
			continue
		}
		keywords = append(keywords, w)
	}
	return keywords
}

// searchGitHistory finds files modified in commits containing the keyword.
func searchGitHistory(repoPath, keyword string) map[string]int {
	files := make(map[string]int)

	// Search for commits with this keyword in message
	cmd := exec.Command("git", "log", "--all", "--oneline", "--grep="+keyword, "-n", "50")
	cmd.Dir = repoPath
	output, err := cmd.Output()
	if err != nil || len(output) == 0 {
		return files
	}

	lines := strings.Split(strings.TrimSpace(string(output)), "\n")
	for _, line := range lines {
		parts := strings.SplitN(line, " ", 2)
		if len(parts) == 0 {
			continue
		}
		commitHash := parts[0]

		// Get files changed in this commit
		filesCmd := exec.Command("git", "diff-tree", "--no-commit-id", "--name-only", "-r", commitHash)
		filesCmd.Dir = repoPath
		filesOutput, err := filesCmd.Output()
		if err != nil {
			continue
		}

		for _, f := range strings.Split(strings.TrimSpace(string(filesOutput)), "\n") {
			if f != "" {
				files[f]++
			}
		}
	}

	return files
}

// ListPersonas returns available persona names.
func (g *Generator) ListPersonas() ([]string, error) {
	reg, err := personas.LoadRegistry(g.oxHome)
	if err != nil {
		return nil, err
	}
	return reg.List(), nil
}

// ListSkills returns available skill names.
func (g *Generator) ListSkills() ([]string, error) {
	entries, err := os.ReadDir(g.skillsDir)
	if err != nil {
		return nil, err
	}

	var skills []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") {
			skills = append(skills, strings.TrimSuffix(e.Name(), ".md"))
		}
	}
	return skills, nil
}
