// Package context generates the AGENTS.md working document for task
// workspaces. Task data (description, hierarchy, notes, history) is
// assembled by yoke (`yoke context`) and embedded verbatim; this package
// adds the ox-owned sections: related files from git history, workspace
// layout, persona, and skills.
package context

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/ashvinbhat/ox/internal/personas"
	"github.com/ashvinbhat/ox/internal/skills"
)

type Generator struct {
	oxHome     string
	personaDir string
	skillsDir  string
}

func NewGenerator(oxHome string) *Generator {
	return &Generator{
		oxHome:     oxHome,
		personaDir: filepath.Join(oxHome, "personas"),
		skillsDir:  filepath.Join(oxHome, "skills"),
	}
}

// TaskContext holds the inputs for generating AGENTS.md.
type TaskContext struct {
	// TaskMarkdown is yoke's assembled task context (`yoke context <ref>`),
	// embedded verbatim as the document's task section.
	TaskMarkdown string

	// Title and Tags drive ox-side features (related-file discovery from
	// git history, skill matching) without re-querying yoke.
	Title string
	Tags  []string

	Persona  string
	Skills   []string // explicitly requested skills
	Repos    []string
	TaskType string // bug, feature, refactor, etc. (for skill matching)
}

// Generate writes AGENTS.md in the workspace and symlinks CLAUDE.md to it.
func (g *Generator) Generate(workspacePath string, ctx *TaskContext) error {
	var sb strings.Builder

	sb.WriteString(strings.TrimRight(ctx.TaskMarkdown, "\n"))
	sb.WriteString("\n\n")

	sb.WriteString("## Task management\n")
	sb.WriteString("Task state lives in yoke — use it directly (no wrapper):\n")
	sb.WriteString("- `yoke note <id> \"...\"` to record progress, decisions, and artifact links as you work\n")
	sb.WriteString("- `yoke context <id>` to reload this task's latest state\n")
	sb.WriteString("- Full command reference: ./YOKE.md\n\n")

	if len(ctx.Repos) > 0 {
		relatedFiles := g.findRelatedFiles(workspacePath, ctx.Repos, ctx.Title)
		if len(relatedFiles) > 0 {
			sb.WriteString("## Related Files (from git history)\n")
			for _, rf := range relatedFiles {
				sb.WriteString(fmt.Sprintf("- %s (%d commits)\n", rf.Path, rf.Commits))
			}
			sb.WriteString("\n")
		}

		sb.WriteString("## Workspace Repos\n")
		for _, r := range ctx.Repos {
			sb.WriteString(fmt.Sprintf("- %s/\n", r))
		}
		sb.WriteString("\n")
	}

	if ctx.Persona != "" {
		sb.WriteString("---\n\n")
		if reg, err := personas.LoadRegistry(g.oxHome); err == nil {
			if p, ok := reg.Get(ctx.Persona); ok {
				sb.WriteString(fmt.Sprintf("# Persona: %s\n", p.Name))
				if p.Role != "" {
					sb.WriteString(fmt.Sprintf("**Role:** %s\n\n", p.Role))
				}
				sb.WriteString(p.Content)
				sb.WriteString("\n")
			}
		}
	}

	g.writeSkills(&sb, workspacePath, ctx)

	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("Generated by ox at %s\n", time.Now().Format(time.RFC3339)))

	agentsPath := filepath.Join(workspacePath, "AGENTS.md")
	if err := os.WriteFile(agentsPath, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("write AGENTS.md: %w", err)
	}

	claudePath := filepath.Join(workspacePath, "CLAUDE.md")
	os.Remove(claudePath)
	if err := os.Symlink("AGENTS.md", claudePath); err != nil {
		return fmt.Errorf("create CLAUDE.md symlink: %w", err)
	}

	return nil
}

// writeSkills auto-injects skills based on tags, persona, and task type.
func (g *Generator) writeSkills(sb *strings.Builder, workspacePath string, ctx *TaskContext) {
	reg, err := skills.LoadRegistry(g.oxHome)
	if err != nil {
		return
	}

	var skillsToInclude []*skills.Skill
	skillNames := make(map[string]bool)

	matched := reg.MatchForTask(ctx.Tags, ctx.Persona, ctx.TaskType)
	for _, s := range matched {
		if !skillNames[s.Name] {
			skillsToInclude = append(skillsToInclude, s)
			skillNames[s.Name] = true
		}
	}

	for _, name := range ctx.Skills {
		if skillNames[name] {
			continue
		}
		if s, ok := reg.Get(name); ok {
			skillsToInclude = append(skillsToInclude, s)
			skillNames[name] = true
		}
	}

	wsSkillsDir := filepath.Join(workspacePath, ".skills")
	if entries, err := os.ReadDir(wsSkillsDir); err == nil {
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
				continue
			}
			name := strings.TrimSuffix(e.Name(), ".md")
			if skillNames[name] {
				continue
			}
			skillsToInclude = append(skillsToInclude, &skills.Skill{
				Name: name,
				File: e.Name(),
			})
			skillNames[name] = true
		}
	}

	if len(skillsToInclude) == 0 {
		return
	}

	sb.WriteString("---\n\n")
	sb.WriteString("# Skills\n\n")

	for _, skill := range skillsToInclude {
		var content string
		wsPath := filepath.Join(workspacePath, ".skills", skill.File)
		if data, err := os.ReadFile(wsPath); err == nil {
			content = string(data)
		} else if c, err := reg.GetContent(skill); err == nil {
			content = c
		} else {
			continue
		}

		sb.WriteString(fmt.Sprintf("## %s\n", skill.Name))
		if skill.Description != "" {
			sb.WriteString(fmt.Sprintf("_%s_\n\n", skill.Description))
		}
		sb.WriteString(content)
		sb.WriteString("\n\n")
	}
}

type RelatedFile struct {
	Path    string
	Commits int
}

// findRelatedFiles searches git history for files related to task keywords.
func (g *Generator) findRelatedFiles(workspacePath string, repos []string, taskTitle string) []RelatedFile {
	var results []RelatedFile

	keywords := extractKeywords(taskTitle)
	if len(keywords) == 0 {
		return nil
	}

	for _, repoName := range repos {
		repoPath := filepath.Join(workspacePath, repoName)
		if _, err := os.Stat(repoPath); err != nil {
			continue
		}

		for _, keyword := range keywords {
			files := searchGitHistory(repoPath, keyword)
			for path, commits := range files {
				fullPath := filepath.Join(repoName, path)
				results = append(results, RelatedFile{Path: fullPath, Commits: commits})
			}
		}
	}

	seen := make(map[string]int)
	for _, rf := range results {
		if existing, ok := seen[rf.Path]; ok {
			if rf.Commits > existing {
				seen[rf.Path] = rf.Commits
			}
		} else {
			seen[rf.Path] = rf.Commits
		}
	}

	var deduped []RelatedFile
	for path, commits := range seen {
		deduped = append(deduped, RelatedFile{Path: path, Commits: commits})
	}

	sort.Slice(deduped, func(i, j int) bool {
		return deduped[i].Commits > deduped[j].Commits
	})

	if len(deduped) > 10 {
		deduped = deduped[:10]
	}

	return deduped
}

func extractKeywords(title string) []string {
	stopWords := map[string]bool{
		"the": true, "a": true, "an": true, "and": true, "or": true,
		"to": true, "for": true, "of": true, "in": true, "on": true,
		"with": true, "add": true, "fix": true, "update": true, "remove": true,
		"implement": true, "refactor": true, "create": true, "make": true,
	}

	words := strings.Fields(strings.ToLower(title))
	var keywords []string
	for _, w := range words {
		w = strings.Trim(w, ".,!?:;()[]{}\"'")
		if len(w) < 3 {
			continue
		}
		if stopWords[w] {
			continue
		}
		keywords = append(keywords, w)
	}
	return keywords
}

// searchGitHistory finds files modified in commits containing the keyword.
func searchGitHistory(repoPath, keyword string) map[string]int {
	files := make(map[string]int)

	cmd := exec.Command("git", "log", "--all", "--oneline", "--grep="+keyword, "-n", "50")
	cmd.Dir = repoPath
	output, err := cmd.Output()
	if err != nil || len(output) == 0 {
		return files
	}

	lines := strings.Split(strings.TrimSpace(string(output)), "\n")
	for _, line := range lines {
		parts := strings.SplitN(line, " ", 2)
		if len(parts) == 0 {
			continue
		}
		commitHash := parts[0]

		filesCmd := exec.Command("git", "diff-tree", "--no-commit-id", "--name-only", "-r", commitHash)
		filesCmd.Dir = repoPath
		filesOutput, err := filesCmd.Output()
		if err != nil {
			continue
		}

		for _, f := range strings.Split(strings.TrimSpace(string(filesOutput)), "\n") {
			if f != "" {
				files[f]++
			}
		}
	}

	return files
}

// ListPersonas returns available persona names.
func (g *Generator) ListPersonas() ([]string, error) {
	reg, err := personas.LoadRegistry(g.oxHome)
	if err != nil {
		return nil, err
	}
	return reg.List(), nil
}

// ListSkills returns available skill names.
func (g *Generator) ListSkills() ([]string, error) {
	entries, err := os.ReadDir(g.skillsDir)
	if err != nil {
		return nil, err
	}

	var names []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") {
			names = append(names, strings.TrimSuffix(e.Name(), ".md"))
		}
	}
	return names, nil
}
