package context

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/ashvinbhat/ox/internal/yoke"
)

// Generator creates CLAUDE.md files for task workspaces.
type Generator struct {
	oxHome      string
	personaDir  string
	skillsDir   string
}

// NewGenerator creates a new context generator.
func NewGenerator(oxHome string) *Generator {
	return &Generator{
		oxHome:     oxHome,
		personaDir: filepath.Join(oxHome, "personas"),
		skillsDir:  filepath.Join(oxHome, "skills"),
	}
}

// TaskContext holds all context for generating CLAUDE.md.
type TaskContext struct {
	Task     *yoke.Task
	Notes    []yoke.Note
	Events   []yoke.Event
	Persona  string
	Skills   []string
	Repos    []string
}

// Generate creates a CLAUDE.md file in the workspace.
func (g *Generator) Generate(workspacePath string, ctx *TaskContext) error {
	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf("# Task #%d: %s\n\n", ctx.Task.Seq, ctx.Task.Title))

	// Status section
	sb.WriteString("## Status\n")
	sb.WriteString(fmt.Sprintf("%s | P%d", strings.ToUpper(string(ctx.Task.Status)), ctx.Task.Priority))
	if len(ctx.Task.Tags) > 0 {
		sb.WriteString(fmt.Sprintf(" | Tags: %s", strings.Join(ctx.Task.Tags, ", ")))
	}
	sb.WriteString("\n\n")

	// Context/Body
	if ctx.Task.Body != "" {
		sb.WriteString("## Context\n")
		sb.WriteString(ctx.Task.Body)
		sb.WriteString("\n\n")
	}

	// Notes
	if len(ctx.Notes) > 0 {
		sb.WriteString("## Notes\n")
		for _, note := range ctx.Notes {
			sb.WriteString(fmt.Sprintf("- %s: %s\n", note.CreatedAt.Format("2006-01-02"), note.Content))
		}
		sb.WriteString("\n")
	}

	// Dependencies (if any blockers)
	if len(ctx.Task.Blockers) > 0 {
		sb.WriteString("## Blocked By\n")
		for _, b := range ctx.Task.Blockers {
			sb.WriteString(fmt.Sprintf("- %s\n", b))
		}
		sb.WriteString("\n")
	}

	// External links
	if ctx.Task.NotionURL != nil && *ctx.Task.NotionURL != "" {
		sb.WriteString("## External\n")
		sb.WriteString(fmt.Sprintf("Notion: %s\n\n", *ctx.Task.NotionURL))
	}

	// Repos in workspace
	if len(ctx.Repos) > 0 {
		sb.WriteString("## Workspace Repos\n")
		for _, r := range ctx.Repos {
			sb.WriteString(fmt.Sprintf("- %s/\n", r))
		}
		sb.WriteString("\n")
	}

	// Persona
	if ctx.Persona != "" {
		sb.WriteString("---\n\n")
		personaContent, err := g.loadPersona(ctx.Persona)
		if err == nil {
			sb.WriteString(personaContent)
			sb.WriteString("\n")
		}
	}

	// Skills
	if len(ctx.Skills) > 0 {
		sb.WriteString("---\n\n")
		sb.WriteString("# Skills\n\n")
		for _, skill := range ctx.Skills {
			skillContent, err := g.loadSkill(skill)
			if err == nil {
				sb.WriteString(fmt.Sprintf("## %s\n", skill))
				sb.WriteString(skillContent)
				sb.WriteString("\n\n")
			}
		}
	}

	// Footer
	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("Generated by ox at %s\n", time.Now().Format(time.RFC3339)))

	// Write file
	claudePath := filepath.Join(workspacePath, "CLAUDE.md")
	return os.WriteFile(claudePath, []byte(sb.String()), 0o644)
}

// loadPersona reads a persona file.
func (g *Generator) loadPersona(name string) (string, error) {
	path := filepath.Join(g.personaDir, name+".md")
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// loadSkill reads a skill file.
func (g *Generator) loadSkill(name string) (string, error) {
	path := filepath.Join(g.skillsDir, name+".md")
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// ListPersonas returns available persona names.
func (g *Generator) ListPersonas() ([]string, error) {
	entries, err := os.ReadDir(g.personaDir)
	if err != nil {
		return nil, err
	}

	var personas []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") {
			personas = append(personas, strings.TrimSuffix(e.Name(), ".md"))
		}
	}
	return personas, nil
}

// ListSkills returns available skill names.
func (g *Generator) ListSkills() ([]string, error) {
	entries, err := os.ReadDir(g.skillsDir)
	if err != nil {
		return nil, err
	}

	var skills []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") {
			skills = append(skills, strings.TrimSuffix(e.Name(), ".md"))
		}
	}
	return skills, nil
}
