package agent

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// GenerateCaptainContext creates the AGENTS.md for the captain agent with planning instructions.
func (m *Manager) GenerateCaptainContext(taskSeq int, taskTitle, taskBody string, repos []string, agentsDir string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Captain: Task #%d — %s\n\n", taskSeq, taskTitle))

	sb.WriteString("## Your Role\n")
	sb.WriteString("You are a CAPTAIN agent. Your job is to analyze this task, explore the codebase, and write a plan.\n")
	sb.WriteString("Do NOT write implementation code. Only produce a plan.\n\n")

	if taskBody != "" {
		sb.WriteString("## Task Description\n")
		sb.WriteString(taskBody)
		sb.WriteString("\n\n")
	}

	sb.WriteString("## Available Repos\n")
	for _, repo := range repos {
		repoPath := filepath.Join(m.oxHome, "repos", repo)
		sb.WriteString(fmt.Sprintf("- %s (at %s)\n", repo, repoPath))
	}
	sb.WriteString("\n")

	// Plan format instructions
	planPath := filepath.Join(agentsDir, "plan.md")
	sb.WriteString("## Instructions\n")
	sb.WriteString(fmt.Sprintf("Write your plan to: %s\n\n", planPath))
	sb.WriteString("The plan MUST follow this exact format:\n\n")
	sb.WriteString("```markdown\n")
	sb.WriteString("# Plan: <task title>\n\n")
	sb.WriteString("## Overview\n")
	sb.WriteString("<1-2 sentence description of the approach>\n\n")
	sb.WriteString("## Agents\n\n")
	sb.WriteString("### <agent-id>\n")
	sb.WriteString("- repo: <repo-name>\n")
	sb.WriteString("- persona: builder\n")
	sb.WriteString("- model: sonnet\n")
	sb.WriteString("- files: [pattern1, pattern2]\n")
	sb.WriteString("- depends_on: []\n")
	sb.WriteString("- description: |\n")
	sb.WriteString("    What this agent should do...\n\n")
	sb.WriteString("### <another-agent-id>\n")
	sb.WriteString("- repo: <repo-name>\n")
	sb.WriteString("- persona: builder\n")
	sb.WriteString("- model: sonnet\n")
	sb.WriteString("- files: [pattern1]\n")
	sb.WriteString("- depends_on: [first-agent-id]\n")
	sb.WriteString("- description: |\n")
	sb.WriteString("    What this agent should do...\n")
	sb.WriteString("```\n\n")

	sb.WriteString("## Rules\n")
	sb.WriteString("- Each agent works in ONE repo only\n")
	sb.WriteString("- File patterns must not overlap between agents\n")
	sb.WriteString("- Agent IDs should be short, descriptive kebab-case (e.g., auth-api, login-ui, db-migration)\n")
	sb.WriteString("- Model should be 'sonnet' for most tasks, 'opus' for complex architecture, 'haiku' for simple tasks\n")
	sb.WriteString("- Use depends_on to specify which agents must finish before this one can start\n")
	sb.WriteString(fmt.Sprintf("- Available repos: %s\n", strings.Join(repos, ", ")))
	sb.WriteString("\n")

	sb.WriteString("## Steps\n")
	sb.WriteString("1. Read the task description above\n")
	sb.WriteString("2. Explore the codebase to understand the current state\n")
	sb.WriteString("3. Break the task into subtasks that can be worked on in parallel\n")
	sb.WriteString("4. Write the plan to the file path above\n")
	sb.WriteString("5. Exit when done\n")

	sb.WriteString(fmt.Sprintf("\n---\nGenerated by ox at %s\n", time.Now().Format(time.RFC3339)))

	return sb.String()
}

// RunCaptainPlanning runs the captain agent non-interactively to produce a plan.
func (m *Manager) RunCaptainPlanning(agentsDir string, repos []string, model string, maxTurns int, maxBudget float64) error {
	planPath := filepath.Join(agentsDir, "plan.md")

	// Build claude command
	prompt := fmt.Sprintf("Read AGENTS.md carefully. Explore the codebase using the repos listed. Then write your plan to %s following the exact format specified in AGENTS.md. When done, exit.", planPath)

	args := []string{
		"-p", prompt,
		"--dangerously-skip-permissions",
	}

	if model != "" {
		args = append(args, "--model", model)
	}
	if maxTurns > 0 {
		args = append(args, "--max-turns", fmt.Sprintf("%d", maxTurns))
	}
	if maxBudget > 0 {
		args = append(args, "--max-budget-usd", fmt.Sprintf("%.2f", maxBudget))
	}

	// Add repo directories for the captain to explore
	for _, repo := range repos {
		repoPath := filepath.Join(m.oxHome, "repos", repo)
		args = append(args, "--add-dir", repoPath)
	}

	cmd := exec.Command("claude", args...)
	cmd.Dir = agentsDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	return cmd.Run()
}
